# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('remark', models.TextField()),
                ('fingerprint', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AmbangInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('img_serial', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('serial', models.CharField(max_length=128)),
                ('is_active', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=128)),
                ('number_plate', models.CharField(max_length=32)),
                ('img_serial', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('remark', models.CharField(max_length=128)),
                ('is_active', models.CharField(max_length=16)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hoapp.Branch', verbose_name='the related branch')),
            ],
        ),
        migrations.CreateModel(
            name='CashboxaplInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('package_num', models.SmallIntegerField(default=0)),
                ('apl_status', models.CharField(max_length=128)),
                ('aplteller', models.CharField(default=0, max_length=128)),
                ('confteller', models.CharField(default=0, max_length=128)),
                ('morning_task_status', models.CharField(max_length=128)),
                ('package_task_status', models.CharField(max_length=128)),
                ('night_task_status', models.CharField(max_length=128)),
                ('is_active', models.CharField(max_length=16)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hoapp.Branch', verbose_name='branch_related')),
                ('cashboxs', models.ManyToManyField(default=1, to='hoapp.Cashbox')),
            ],
        ),
        migrations.CreateModel(
            name='RouteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('modify_date', models.DateField(auto_now=True)),
                ('is_active', models.CharField(max_length=16)),
                ('routes', models.ManyToManyField(default=1, to='hoapp.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_task_status', models.CharField(max_length=128)),
                ('task_task_status', models.CharField(max_length=128)),
                ('ambs', models.ManyToManyField(to='hoapp.AmbangInfo')),
                ('car_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hoapp.CarInfo')),
                ('cinfo', models.ManyToManyField(to='hoapp.CashboxaplInfo')),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hoapp.RouteInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AssistInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('hoapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('hoapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hoapp.Branch', verbose_name='u_bpk'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='assists',
            field=models.ManyToManyField(to='hoapp.AssistInfo'),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='majors',
            field=models.ManyToManyField(to='hoapp.MajorInfo'),
        ),
    ]
