# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0002_remove_carinfo_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='number_plate',
            field=models.CharField(max_length=128),
        ),
    ]
