# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0003_auto_20170626_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hoapp.Branch', verbose_name='u_bpk'),
        ),
    ]
