# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0005_auto_20170626_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoapp.Branch', verbose_name='u_bpk'),
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='routes',
            field=models.ManyToManyField(to='hoapp.Branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoapp.Branch', verbose_name='u_bpk'),
        ),
    ]
