# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoapp', '0006_auto_20170626_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxaplinfo',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoapp.Branch', verbose_name='branch_related'),
        ),
    ]
