# -*- coding:utf-8 -*-
from nose.tools import eq_, raises, assert_true
from sqlalchemy.orm import aliased
import unittest
import json
import time
import logging

from ..model.common import *
from ..model.party import *
from ..model.customer import *
from sys import modules
import datetime
import random

log = logging.getLogger()
class TestCustomerInfo(unittest.TestCase):
    def setUp(self):
        logging.debug("执行setup")
        self.session=simple_session()
        Base.metadata.create_all(self.session.bind)

    def insertTarget(self):
        #logging.debug("inini") 
        cust_target = CustTarget(cust_type=u'个人客户',cust_id=1)

        age = Target(cust_target=cust_target,name=u'年龄',code='age')
        age_attr1 = Attribute(target=age,score=1,name=u'22岁以下(含22岁),55岁以上')
        age_attr2 = Attribute(target=age,score=2,name=u'22岁－25岁(含25岁),50岁－55岁(含55岁)')
        age_attr3 = Attribute(target=age,score=3,name=u'25岁－30岁(含30岁),45岁－50岁(含50岁)')
        age_attr4 = Attribute(target=age,score=4,name=u'30岁－35岁(含35岁)')
        age_attr5 = Attribute(target=age,score=5,name=u'35岁－45岁(含45岁)')
        self.session.add_all([age_attr1,age_attr2,age_attr3,age_attr4,age_attr5]) 

        hea_aca = Target(cust_target=cust_target,name=u'职称或最高学历',code=u'headship_academic')
        hea_aca_atrr1 = Attribute(target=hea_aca,score=5,name=u'高级职称或博士学位')
        hea_aca_atrr2 = Attribute(target=hea_aca,score=4,name=u'硕士或双学士学位')
        hea_aca_atrr3 = Attribute(target=hea_aca,score=3,name=u'中级职称或学士学位')
        hea_aca_atrr4 = Attribute(target=hea_aca,score=2,name=u'其它')
        self.session.add_all([hea_aca_atrr1,hea_aca_atrr2,hea_aca_atrr3,hea_aca_atrr4]) 
        
        #self.session.commit()
        #logging.debug(self.session.query(Party.name).first()[0])
    def createfhdsckfhz(self):
        
        
        u''' 对私分户账   '''
        tab_name = 'fhdsckfhz'
        tb = CreateTable(table_name=tab_name,element='jgbm',attr='String',lenth=32,explain=u'机构编码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zh',attr='String',lenth=32,explain=u'账号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fzh',attr='String',lenth=16,explain=u'分账号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bsh',attr='BigInteger',lenth=32,dcm=0,explain=u'标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=16,explain=u'币种')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hm',attr='String',lenth=32,explain=u'户名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='kmkzz',attr='String',lenth=16,explain=u'科目控制字')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ye',attr='String',lenth=32,dcm=2,explain=u'余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zrye',attr='String',lenth=32,dcm=2,explain=u'昨日余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='mxye',attr='String',lenth=32,dcm=2,explain=u'明细余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='cz',attr='String',lenth=16,explain=u'储种')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='mm',attr='String',lenth=16,explain=u'密码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlx',attr='String',lenth=16,explain=u'证件类型')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjhm',attr='String',lenth=32,explain=u'证件号码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zqfs',attr='String',lenth=16,explain=u'支取方式')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zhzl',attr='String',lenth=16,explain=u'账户种类')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pzzl',attr='String',lenth=16,explain=u'凭证种类')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pzh',attr='String',lenth=32,explain=u'凭证号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dlbz',attr='String',lenth=32,explain=u'代理标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dyhs',attr='String',lenth=32,explain=u'打印行数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='szye',attr='String',lenth=32,dcm=2,explain=u'上折余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='mxbs',attr='String',lenth=32,explain=u'明细笔数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='wdbs',attr='String',lenth=32,explain=u'未打笔数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yefx',attr='String',lenth=16,explain=u'余额方向')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fsefx',attr='String',lenth=16,explain=u'发生额方向')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='sbfsrq',attr='String',lenth=16,dcm=0,explain=u'上笔发生日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='kzje',attr='String',lenth=32,dcm=2,explain=u'控制金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='djje',attr='String',lenth=32,dcm=2,explain=u'冻结金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='je1',attr='String',lenth=32,dcm=2,explain=u'金额1,整零-开户金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='je2',attr='String',lenth=32,dcm=2,explain=u'金额2')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxjs',attr='String',lenth=32,dcm=2,explain=u'利息积数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fdbl',attr='String',lenth=16,dcm=6,explain=u'浮动比率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='khrq',attr='String',lenth=16,dcm=0,explain=u'开户日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqrq',attr='String',lenth=16,dcm=0,explain=u'到期日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='cq',attr='String',lenth=32,explain=u'存期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jgys',attr='String',lenth=32,explain=u'间隔月数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zcs',attr='String',lenth=32,explain=u'总次数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yfscs',attr='String',lenth=32,explain=u'已发生次数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ybtcs',attr='String',lenth=32,explain=u'已部提次数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yhzcs',attr='String',lenth=32,explain=u'已换折次数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yytlx',attr='String',lenth=32,dcm=2,explain=u'已预提利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xgbsh',attr='String',lenth=32,dcm=0,explain=u'相关标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='chbz',attr='String',lenth=16,explain=u'钞汇标志 0-钞户1-汇户')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jxbz',attr='String',lenth=16,explain=u'计息标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zhzt',attr='String',lenth=16,explain=u'帐户状态')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='tsbz',attr='String',lenth=32,explain=u'特殊标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yykzye',attr='String',lenth=32,dcm=2,explain=u'预约控制余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yybz',attr='String',lenth=16,explain=u'预约定期户标志 1-是0-非')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zryebz',attr='String',lenth=16,explain=u'昨日余额处理标志 0-未处理1-已处理')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='scrq',attr='String',lenth=16,dcm=0,explain=u'生成日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jgbh',attr='String',lenth=16,dcm=0,explain=u'柜组编号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='my',attr='String',lenth=32,explain=u'密押')
        self.session.add(tb)




    def createfhdkfhz(self):
        u''' 贷款分户账   '''
        tab_name = 'fhdkfhz'
        tb = CreateTable(table_name=tab_name,element='jgdm',attr='String',lenth=32,explain=u'机构编码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zh',attr='String',lenth=32,explain=u'帐号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,explain=u'标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bz',attr='String',lenth=16,explain=u'币种')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hm',attr='String',lenth=64,explain=u'户名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='kmkzz',attr='String',lenth=16,explain=u'科目控制字')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ye',attr='String',lenth=32,dcm=2,explain=u'余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zrye',attr='String',lenth=32,dcm=2,explain=u'昨日余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='mxye',attr='String',lenth=32,dcm=2,explain=u'明细余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zbdm',attr='String',lenth=32,explain=u'指标代码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='htxh',attr='String',lenth=32,explain=u'合同序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='mxbs',attr='String',lenth=32,explain=u'明细笔数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='myys',attr='String',lenth=32,explain=u'满页页数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dked',attr='String',lenth=32,dcm=2,explain=u'贷款额度')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jjje',attr='String',lenth=32,dcm=2,explain=u'借据金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=6,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fdbl',attr='String',lenth=16,dcm=6,explain=u'浮动比率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yqll',attr='String',lenth=16,dcm=6,explain=u'逾期利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='nyll',attr='String',lenth=16,dcm=6,explain=u'挪用利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='nybz',attr='String',lenth=16,explain=u'挪用标志 0-挪用 1-非挪用')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bnfl',attr='String',lenth=16,dcm=6,explain=u'表内复利利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bwfl',attr='String',lenth=16,dcm=6,explain=u'表外复利利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='khrq',attr='String',lenth=16,dcm=0,explain=u'开户日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jxbz',attr='String',lenth=16,explain=u'计息标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkyt',attr='String',lenth=64,explain=u'贷款用途')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqrq',attr='String',lenth=16,dcm=0,explain=u'到期日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='sbfsrq',attr='String',lenth=16,dcm=0,explain=u'上笔发生日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxjs',attr='String',lenth=32,dcm=2,explain=u'利息积数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ljhse',attr='String',lenth=32,dcm=2,explain=u'本金积累回收额,清户时存积数(撤销用)')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxhse',attr='String',lenth=32,dcm=2,explain=u'利息回收额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dklx',attr='String',lenth=16,explain=u'贷款类型')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xmdm',attr='String',lenth=16,explain=u'项目代码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qyrq',attr='String',lenth=16,dcm=0,explain=u'签约日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyrq',attr='String',lenth=16,dcm=0,explain=u'转逾日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bnbsh',attr='String',lenth=32,dcm=0,explain=u'表内利息标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bwbsh',attr='String',lenth=32,dcm=0,explain=u'表外利息标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='flbsh',attr='String',lenth=32,dcm=0,explain=u'复利标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ckbsh',attr='String',lenth=32,dcm=0,explain=u'存款户标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zcbsh',attr='String',lenth=32,dcm=0,explain=u'转存户标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xybh',attr='String',lenth=32,explain=u'担保,抵押等协议编号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dybsh',attr='String',lenth=32,dcm=0,explain=u'抵押户标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zqbz',attr='String',lenth=16,explain=u'展期标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zqll',attr='String',lenth=16,dcm=6,explain=u'展期利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zqdqrq',attr='String',lenth=16,dcm=0,explain=u'展期到期日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zhzt',attr='String',lenth=16,explain=u'账户状态')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='tsbz',attr='String',lenth=32,explain=u'特殊标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='czbh',attr='String',lenth=32,explain=u'储种编号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zryebz',attr='String',lenth=16,explain=u'昨日余额处理标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jgbh',attr='String',lenth=16,explain=u'机构编号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txrq',attr='String',lenth=16,dcm=0,explain=u'调息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='my',attr='String',lenth=32,explain=u'密押')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='khh',attr='String',lenth=32,dcm=0,explain=u'客户号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yqbj',attr='String',lenth=32,dcm=2,explain=u'逾期本金')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dzbj',attr='String',lenth=32,dcm=2,explain=u'呆滞本金')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ddbj',attr='String',lenth=32,dcm=2,explain=u'呆账本金')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bnlx',attr='String',lenth=32,dcm=2,explain=u'表内利息,宽限期内的利息不可累加到此字段')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bwlx',attr='String',lenth=32,dcm=2,explain=u'表外利息,宽限期内的利息不可累加到此字段')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='tqrq',attr='String',lenth=16,dcm=0,explain=u'提取日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='biz_type',attr='String',lenth=16,explain=u'信贷产品号,核心批量文件不要为这个字段赋值,只保留位置')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='biz_name',attr='String',lenth=64,explain=u'产品中文名字')
        self.session.add(tb)

    def createcdhpdjb(self):
        u''' 承兑汇票登记簿   '''
        tab_name = 'cdhpdjb'
        tb = CreateTable(table_name=tab_name,element='jgbm',attr='String',lenth=32,explain=u'机构编码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hplx',attr='String',lenth=16,explain=u'汇票类型')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hphm',attr='String',lenth=32,explain=u'汇票号码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xybh',attr='String',lenth=32,explain=u'协议编号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xyxh',attr='String',lenth=32,explain=u'协议序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='cprzh',attr='String',lenth=32,explain=u'出票人帐号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='cprhm',attr='String',lenth=64,explain=u'出票人户名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='cphhh',attr='String',lenth=32,explain=u'出票人行号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='cphhm',attr='String',lenth=64,explain=u'出票人行名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='skrzh',attr='String',lenth=32,explain=u'收款人帐号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='skrhm',attr='String',lenth=64,explain=u'收款人户名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='skhhh',attr='String',lenth=32,explain=u'收款人行号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='skhhm',attr='String',lenth=64,explain=u'收款人行名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hpje',attr='String',lenth=32,dcm=2,explain=u'汇票金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yqje',attr='String',lenth=32,dcm=2,explain=u'逾期金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ztbz',attr='String',lenth=32,explain=u'状态标志 1-签发 2-兑付 4-挂失 5-扣款 6-转逾期 7-未用退回')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='cprq',attr='String',lenth=16,dcm=0,explain=u'出票日期,重要字段,征信上报时的提取条件')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqrq',attr='String',lenth=16,dcm=0,explain=u'到票日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zfrq',attr='String',lenth=16,dcm=0,explain=u'支付日期,重要字段,征信提取业务变更时的检索条件,签发时为0,各种结清态时为状态变化时的日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyrq',attr='String',lenth=16,dcm=0,explain=u'转逾日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bzkxyt',attr='String',lenth=64,explain=u'备注款项用途')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='my',attr='String',lenth=16,explain=u'密押')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fj',attr='String',lenth=32,explain=u'默认为空')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='czy',attr='String',lenth=16,explain=u'操作员')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bzjzh',attr='String',lenth=32,explain=u'保证金帐号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bzje',attr='String',lenth=32,dcm=2,explain=u'保证金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyjzh',attr='String',lenth=32,explain=u'质押金帐号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyje',attr='String',lenth=32,dcm=2,explain=u'质押金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=6,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkzh',attr='String',lenth=32,explain=u'贷款账号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='thrq',attr='String',lenth=16,dcm=0,explain=u'未用退回日期,重要字段,征信提取业务变更时的检索条件')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jyhtbh',attr='String',lenth=64,explain=u'合同编号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fphm',attr='String',lenth=64,explain=u'发票号码')
        self.session.add(tb)
    def createdjdkfdjs(self):
        u''' 贷款分段积数表   '''
        tab_name = 'djdkfdjs'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='rq',attr='String',lenth=16,dcm=0,explain=u'日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=0,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxjs',attr='String',lenth=32,dcm=2,explain=u'利息积数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxzl',attr='String',lenth=16,explain=u'利息种类 0-表内息1-表内逾期息2-表外息3-表外复利')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lsrq',attr='String',lenth=16,dcm=0,explain=u'流水日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bz',attr='String',lenth=16,explain=u'标志0-正常1-已计息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='htxh',attr='String',lenth=32,explain=u'合同序号')
        self.session.add(tb)
    def createdjtx(self):
        u''' 登记贴现   '''
        tab_name = 'djtx'
        tb = CreateTable(table_name=tab_name,element='jgbm',attr='String',lenth=32,explain=u'机构编码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=9,dcm=0,explain=u'贴现标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xh',attr='String',lenth=32,explain=u'序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hth',attr='String',lenth=32,explain=u'合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pjdqr',attr='String',lenth=16,dcm=0,explain=u'票据到期日')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txdqr',attr='String',lenth=16,dcm=0,explain=u'贴现到期日')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pmje',attr='String',lenth=32,dcm=2,explain=u'票面金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pjmc',attr='String',lenth=16,explain=u'票据名称')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pjhm',attr='String',lenth=32,explain=u'票据号码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dfyh',attr='String',lenth=64,explain=u'对付银行')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qfrhm',attr='String',lenth=64,explain=u'签发人户名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qfrzh',attr='String',lenth=32,explain=u'签发人账号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txrhm',attr='String',lenth=64,explain=u'贴现人户名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txrzh',attr='String',lenth=32,explain=u'贴现人帐号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txl',attr='String',lenth=16,dcm=6,explain=u'贴现率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txr',attr='String',lenth=16,dcm=0,explain=u'贴现日')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pjzt',attr='String',lenth=16,explain=u'票据状态')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lsrq',attr='String',lenth=16,dcm=0,explain=u'流水日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bsh1',attr='String',lenth=32,dcm=0,explain=u'标识号1')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bsh2',attr='String',lenth=32,dcm=0,explain=u'标识号2')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txje',attr='String',lenth=32,dcm=2,explain=u'贴现金额,票面金额-利息')
        self.session.add(tb)
    def createsxdkmx(self):
        u''' 授信贷款明细表(对私)   '''
        tab_name = 'sxdkmx'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=9,dcm=0,explain=u'标识号,额度账户bsh')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xh',attr='String',lenth=32,explain=u'序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ffrq',attr='String',lenth=16,dcm=0,explain=u'发放日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqrq',attr='String',lenth=16,dcm=0,explain=u'到期日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hkrq',attr='String',lenth=16,dcm=0,explain=u'还款日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyrq',attr='String',lenth=16,dcm=0,explain=u'转逾日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dzrq',attr='String',lenth=16,dcm=0,explain=u'呆滞日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ddrq',attr='String',lenth=16,dcm=0,explain=u'呆账日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bz',attr='String',lenth=16,explain=u'标志:0-未结清 1-结清 2-撤销')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dked',attr='String',lenth=32,dcm=2,explain=u'贷款额度')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fse',attr='String',lenth=32,dcm=2,explain=u'发生额,bz为结清时,发生额必须为0')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=6,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yqll',attr='String',lenth=16,dcm=6,explain=u'逾期利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='nyll',attr='String',lenth=16,dcm=6,explain=u'挪用利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lx',attr='String',lenth=32,dcm=2,explain=u'利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lsrq',attr='String',lenth=16,dcm=0,explain=u'流水日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zt',attr='String',lenth=16,explain=u'状态:0-正常1-逾期2-呆滞3-呆账4-核销5-挪用')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='tsbz',attr='String',lenth=16,explain=u'特殊标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zh',attr='String',lenth=32,explain=u'帐号')
        self.session.add(tb)
    def createsxdkls(self):
        u''' 授信贷款流水表(对私)   '''
        tab_name = 'sxdkls'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'标识号,额度账户bsh')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xh',attr='String',lenth=32,explain=u'序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='rq',attr='String',lenth=16,dcm=0,explain=u'日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bjfse',attr='String',lenth=32,dcm=2,explain=u'本金发生额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxfse',attr='String',lenth=32,dcm=2,explain=u'利息发生额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zzrq',attr='String',lenth=16,dcm=0,explain=u'支取日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ts',attr='String',lenth=32,explain=u'天数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxjs',attr='String',lenth=32,dcm=2,explain=u'利息积数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=6,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jylx',attr='String',lenth=16,explain=u'交易类型1-放贷2-结息3-还本息4-还本金5-还复利*-撤销6-核销本金7-核销利息8-核销收回本金9-核销收回利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
    def createsxdkmxn(self):
        u''' 授信贷款明细表(对公)   '''
        tab_name = 'sxdkmxn'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'贷款标识号,额度账户bsh')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='kh',attr='String',lenth=32,explain=u'卡号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xh',attr='String',lenth=32,explain=u'序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ffrq',attr='String',lenth=16,dcm=0,explain=u'发放日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqrq',attr='String',lenth=16,dcm=0,explain=u'到期日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hkrq',attr='String',lenth=16,dcm=0,explain=u'还款日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyrq',attr='String',lenth=16,dcm=0,explain=u'转逾日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dzrq',attr='String',lenth=16,dcm=0,explain=u'呆滞日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ddrq',attr='String',lenth=16,dcm=0,explain=u'呆账日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bz',attr='String',lenth=16,explain=u'标志,第一位0-未还清1-还清*-撤销')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dked',attr='String',lenth=32,dcm=2,explain=u'贷款额度')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fse',attr='String',lenth=32,dcm=2,explain=u'发生额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=6,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yqll',attr='String',lenth=16,dcm=6,explain=u'逾期利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='nyll',attr='String',lenth=16,dcm=6,explain=u'挪用利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zqll',attr='String',lenth=16,dcm=6,explain=u'展期利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lx',attr='String',lenth=32,dcm=2,explain=u'利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lsrq',attr='String',lenth=16,dcm=0,explain=u'流水日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zhlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zt',attr='String',lenth=16,explain=u'状态,0-正常2-逾期4-呆滞5-呆账6-核销7-挪用')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zqbz',attr='String',lenth=16,explain=u'展期标志1-非展期0-展期,展期到期日期放到到期日期字段')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='nybz',attr='String',lenth=16,explain=u'挪用标志1-非挪用0-挪用')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qx',attr='String',lenth=32,explain=u'期限,与sxdkdzbn中期限一致')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lbh',attr='String',lenth=16,explain=u'类别号,与fhdkfhz中czbh一致')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txfs',attr='String',lenth=16,explain=u'调息方式,0-不自动调息2-按月调息3-按季调息4-按年调息5-按贷款分户账调息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txrq',attr='String',lenth=16,dcm=0,explain=u'下次调整日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='tsbz',attr='String',lenth=32,explain=u'特殊标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zh',attr='String',lenth=32,explain=u'帐号')
        self.session.add(tb)
    def createsxdklsn(self):
        u''' 授信贷款流水表(对公)   '''
        tab_name = 'sxdklsn'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'贷款标识号,额度账户bsh')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='kh',attr='String',lenth=32,explain=u'卡号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xh',attr='String',lenth=32,explain=u'序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='rq',attr='String',lenth=16,dcm=0,explain=u'日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bjfse',attr='String',lenth=32,dcm=2,explain=u'本金发生额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxfse',attr='String',lenth=32,dcm=2,explain=u'利息发生额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zzrq',attr='String',lenth=16,dcm=0,explain=u'终止日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ts',attr='String',lenth=32,explain=u'天数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxjs',attr='String',lenth=32,dcm=2,explain=u'利息积数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=6,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jylx',attr='String',lenth=16,explain=u'交易类型')
	#0关联1授信2计息3还息4还款5调整利率6更改状态A挪用B取消挪用C展期D取消展期E转正常F转逾期G转呆滞H转呆账9销户I核销本金J核销利息K核销收回本金L核销收回利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
    def createdjajhkjhb(self):
        u''' 按揭还款计划表   '''
        tab_name = 'djajhkjhb'
        tb = CreateTable(table_name=tab_name,element='jgbm',attr='String',lenth=32,explain=u'机构编码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hkfs',attr='String',lenth=16,explain=u'还款方式-同ggdkcsb.hkfs')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zdkk',attr='String',lenth=16,explain=u'自动扣款标志1-自动扣款0-柜台还款')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zje',attr='String',lenth=32,dcm=2,explain=u'总金额-生成还款计划的原始本金')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjqs',attr='String',lenth=16,dcm=0,explain=u'还款总期数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qhje',attr='String',lenth=32,dcm=2,explain=u'每期应还金额合计')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qhbj',attr='String',lenth=32,dcm=2,explain=u'期还本金')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qhlx',attr='String',lenth=32,dcm=2,explain=u'期还利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bhed',attr='String',lenth=16,dcm=2,explain=u'变化额度-期还额变化情况,用于等额变化方式')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zhzt',attr='String',lenth=16,explain=u'贷款状态1-是0-否')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqqc',attr='String',lenth=16,dcm=0,explain=u'当前期次-当前待处理期次，还款日或转逾日更新')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqzt',attr='String',lenth=16,explain=u'当前状态')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='yqbsh',attr='String',lenth=32,dcm=0,explain=u'逾期半年以内标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ybbsh',attr='String',lenth=32,dcm=0,explain=u'逾期半年以上标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='djrq',attr='String',lenth=16,dcm=0,explain=u'登记日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyrq',attr='String',lenth=16,dcm=0,explain=u'转逾日期-本期最后还款日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zxrq',attr='String',lenth=16,dcm=0,explain=u'销户日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='sjzjqs',attr='String',lenth=16,dcm=0,explain=u'实际总计期数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='shdqqc',attr='String',lenth=16,dcm=0,explain=u'实际当前期数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='htxh',attr='String',lenth=32,explain=u'合同序号')
        self.session.add(tb)
    def createsxdkqx(self):
        u''' 授信贷款欠息表(对私)   '''
        tab_name = 'sxdkqx'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'标识号,额度账户bsh')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xh',attr='String',lenth=32,explain=u'序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jxrq',attr='String',lenth=16,dcm=0,explain=u'计息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zzrq',attr='String',lenth=16,dcm=0,explain=u'支取日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ts',attr='String',lenth=32,explain=u'天数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxjs',attr='String',lenth=32,dcm=2,explain=u'利息积数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=6,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lx',attr='String',lenth=32,dcm=2,explain=u'利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bz',attr='String',lenth=16,explain=u'标志:0-未结清1-结清')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lsrq',attr='String',lenth=16,dcm=0,explain=u'流水日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水行号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='tsbz',attr='String',lenth=16,explain=u'特殊标志')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
    def createsxfdjs(self):
        u''' 授信贷款分段积数表(对私)   '''
        tab_name = 'sxfdjs'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'标识号,额度账户bsh')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='xh',attr='String',lenth=32,explain=u'序号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='rq',attr='String',lenth=16,dcm=0,explain=u'日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ll',attr='String',lenth=16,dcm=6,explain=u'利率')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxjs',attr='String',lenth=32,dcm=2,explain=u'利息积数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lsrq',attr='String',lenth=16,dcm=0,explain=u'流水日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bz',attr='String',lenth=16,explain=u'标志:0-未结清*-结清')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
    def createdjajqkb(self):
        u''' 按揭欠款表(存量)   '''
        tab_name = 'djajqkb'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqqc',attr='String',lenth=16,dcm=0,explain=u'欠款期次')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='sjdqqc',attr='String',lenth=16,dcm=0,explain=u'实际欠款期次')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hkqc',attr='String',lenth=16,dcm=0,explain=u'欠款年月')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hkrq',attr='String',lenth=16,dcm=0,explain=u'还款日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bj',attr='String',lenth=32,dcm=2,explain=u'欠本金')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lx',attr='String',lenth=32,dcm=2,explain=u'欠利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bnqx',attr='String',lenth=32,dcm=2,explain=u'表内欠息(不使用)')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bwqx',attr='String',lenth=32,dcm=2,explain=u'表外欠息(不使用)')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bwfl',attr='String',lenth=32,dcm=2,explain=u'表外复利-复利或罚息(不使用)')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zhzt',attr='String',lenth=16,explain=u'还前状态1-正常2-逾期半年以内3-逾期半年以上')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyrq',attr='String',lenth=16,dcm=0,explain=u'转逾日期,重要字段，提取个证时间段所欠本金')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lsrq',attr='String',lenth=16,dcm=0,explain=u'流水日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=16,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='czy',attr='String',lenth=16,explain=u'操作员')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='htxh',attr='String',lenth=16,explain=u'合同序号')
        self.session.add(tb)
    def createdjajhkb(self):
        u''' 按揭还款表(增量)   '''
        tab_name = 'djajhkb'
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'贷款标识')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dqqc',attr='String',lenth=16,dcm=0,explain=u'还款期次')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='sjdqqc',attr='String',lenth=16,dcm=0,explain=u'实际还款期次')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hkqc',attr='String',lenth=16,dcm=0,explain=u'应还款年月,若为提前还款此值必须为0')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='hkrq',attr='String',lenth=16,dcm=0,explain=u'还款日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bj',attr='String',lenth=32,dcm=2,explain=u'本金')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lx',attr='String',lenth=32,dcm=2,explain=u'利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bnqx',attr='String',lenth=32,dcm=2,explain=u'表内欠息(不使用)')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bwqx',attr='String',lenth=32,dcm=2,explain=u'表外欠息(不使用)')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bwfl',attr='String',lenth=32,dcm=2,explain=u'表外复利-复利或罚息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zhzt',attr='String',lenth=16,explain=u'还前状态1-正常2-逾期半年以内3-逾期半年以上')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zyzq',attr='String',lenth=16,dcm=0,explain=u'转逾日期-转逾月的21号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lsrq',attr='String',lenth=16,dcm=0,explain=u'流水日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='czy',attr='String',lenth=16,explain=u'操作员')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='htxh',attr='String',lenth=32,explain=u'合同序号')
        self.session.add(tb)
    def createfhdkmxz(self):
        u'''  贷款分户明细   '''
        tab_name = 'fhdkmxz'
        tb = CreateTable(table_name=tab_name,element='jgbm',attr='String',lenth=32,explain=u'机构编码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jyjgh',attr='String',lenth=32,explain=u'交易机构号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zjlsh',attr='String',lenth=32,explain=u'主机流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='wdlsh',attr='String',lenth=32,explain=u'网点流水号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jylsbc',attr='String',lenth=32,explain=u'交易流水笔次')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bsh',attr='String',lenth=32,dcm=0,explain=u'标识号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='kmkzz',attr='String',lenth=16,explain=u'科目控制字')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jydm',attr='String',lenth=16,explain=u'交易代码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jdbz',attr='String',lenth=16,explain=u'借贷标志0-非记账1-借2-贷')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fse',attr='String',lenth=32,dcm=2,explain=u'发生额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='ye',attr='String',lenth=32,dcm=2,explain=u'账户余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='sbye',attr='String',lenth=32,dcm=2,explain=u'上笔余额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='lxjs',attr='String',lenth=32,dcm=2,explain=u'利息积数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jyrq',attr='String',lenth=16,dcm=0,explain=u'交易日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jysj',attr='String',lenth=32,explain=u'交易时间(HHMMSS)')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='qxrq',attr='String',lenth=16,dcm=0,explain=u'起息日期')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pzzl',attr='String',lenth=16,explain=u'凭证种类')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='pzh',attr='String',lenth=32,explain=u'凭证号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='zy',attr='String',lenth=32,explain=u'摘要')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='czy',attr='String',lenth=16,explain=u'记帐员')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='fhy',attr='String',lenth=16,explain=u'复核员')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='mxbs',attr='String',lenth=32,explain=u'明细笔数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='myys',attr='String',lenth=32,explain=u'满页页数')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bz',attr='String',lenth=16,explain=u'标志0-非记账1-现金2-转账')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dybz',attr='String',lenth=16,explain=u'打印标志0-未打印1-已打存折2-已打对账单')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkhth',attr='String',lenth=32,explain=u'贷款合同号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='htxh',attr='String',lenth=32,explain=u'合同序号')
        self.session.add(tb)
        #---------------------------------------------------------------------------------------------------------------
        tb = CreateTable(table_name=tab_name,element='yelx',attr='String',lenth=16,explain=u'业务类型1-本金2-利息')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='jylx',attr='String',lenth=16,explain=u'交易类型:0-贷款发放1-正常归还2-冲正3-核销4-核销收回')
        self.session.add(tb) #当日撤销不提,但分户账的zhzt第一位要赋值D
    def createdskhxxwj_contrast(self):
        u''' 对私客户信息对照文件(存量)   '''
        tab_name = 'dskhxxwj_contrast'
        tb = CreateTable(table_name=tab_name,element='core_cus_id',attr='String',lenth=32,explain=u'核心客户号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='per_name',attr='String',lenth=64,explain=u'客户名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='id_type',attr='String',lenth=32,explain=u'证件类型51-身份证52-居民户口薄54军人身份证55-武装警察身份证99-其他')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='id_no',attr='String',lenth=32,explain=u'证件号码')
        self.session.add(tb)
    def createdkkhdzb(self):
        u''' 贷款卡号对照表(存量)   '''
        tab_name = 'dkkhdzb'
        tb = CreateTable(table_name=tab_name,element='pjhm',attr='String',lenth=32,explain=u'票据号码')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='dkkh',attr='String',lenth=32,explain=u'贷款卡号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='txje',attr='String',lenth=32,dcm=2,explain=u'金额')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='bz',attr='String',lenth=16,explain=u'标志 1-贴现 2-承兑')
        self.session.add(tb)
    def createdgkhxxwj_contrast(self):
        u''' 对公客户信息对照文件(存量)   '''
        tab_name = 'dgkhxxwj_contrast'
        tb = CreateTable(table_name=tab_name,element='core_cus_id',attr='String',lenth=32,explain=u'核心客户号')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='cn_com_name',attr='String',lenth=128,explain=u'客户名')
        self.session.add(tb)
        tb = CreateTable(table_name=tab_name,element='org_id',attr='String',lenth=32,explain=u'代码证号')
        self.session.add(tb)

    def testPersonLevel(self):
        '''
        self.createfhdkfhz()
        self.createcdhpdjb()
        self.createdjdkfdjs()
        self.createdjtx()
        self.createsxdkmx()
        self.createsxdkls()
        self.createsxdkmxn()
        self.createsxdklsn()
        self.createdjajhkjhb()
        self.createsxdkqx()
        self.createsxfdjs()
        self.createdjajqkb()
        self.createdjajhkb()
        self.createfhdkmxz()
        self.createdskhxxwj_contrast()
        self.createdkkhdzb()
        self.createdgkhxxwj_contrast()
        '''
        q = self.session.query(Party).limit(10).all()
        log.debug(q)
        #self.createLocal('fhdkfhz')
        #self.createfhdkfhz()

        filenames = [['fhdkfhz',u'贷款分户账'],['cdhpdjb',u'承兑汇票登记簿'],['djdkfdjs',u'贷款分段积数表(存量)'],['djtx',u'登记贴现'],['sxdkmx',u'授信贷款明细表（对私）'],['sxdkls',u'授信贷款流水表（对私）'],['sxdkmxn',u'授信贷款明细表（对公）'],['sxdklsn',u'授信贷款流水表(对公)'],['djajhkjhb',u'按揭还款计划表（村量）'],['sxdkqx',u'授信贷款欠息表（对私）'],['sxfdjs',u'授信贷款分段积数表'],['djajqkb',u'按揭欠款表（存量）'],['djajhkb',u'按揭还款表(增量)'],['fhdkmxz',u'贷款分户明细'],['dskhxxwj_contrast',u'对私客户信息对照文件'],['dkkhdzb',u'贷款卡号对照表'],['dgkhxxwj_contrast',u'对公客户信息对照文件']]
        for it in filenames:
            self.createLocal(it[0],it[1])

        #cust = self.session.query(Customer).first()
        #logging.debug( per_leve.__dict__) 
        #logging.debug( vars(personLevel) ) 

    def createLocal(self,tab_name,explain):
        #tab_name = 'fhdsckfhz'
        fhdsckfhz_eles  = self.session.query(CreateTable).filter(CreateTable.table_name == tab_name ).order_by(CreateTable.id).all()
        fls = open('table.py','aw')
        tb_str = u"class %s(Base):\n    u'''  %s  '''\n    __tablename__='%s'\n    id = Column(BigInteger,Sequence('%s_seq_id'),primary_key=True)\n"%(tab_name.upper(),explain,tab_name,tab_name)
        fls.write(tb_str.encode('utf-8'))
        for ele in fhdsckfhz_eles:
            sql=u"    %s = Column(String(%s),doc=u'%s')\n"%(ele.element,ele.lenth,ele.explain)
            fls.write(sql.encode('utf-8'))
            logging.debug(sql)

    def tearDown(self):
        #self.session.rollback()
        #Base.metadata.drop_all(self.session.bind)
        self.session.commit()    
