# -*- coding:utf-8 -*-
from nose.tools import eq_, raises, assert_true
from sqlalchemy.orm import aliased
import unittest
import json
import time
import logging
from sys import modules
import datetime
import random
from ..model.user import *
from ..model.party import *
from ..model.asset import *
from ..model.liabilities import *
from ..model.customer import *
from ..model.transaction import *
from ..model.task import *
from ..model.branch import *
from ..model.approve import *
from ..model.img import *
from ..model.application import *
from ..model.common import *
from ..model.guarantee import *
from ..model.contract import *
from ..model.creditLevel import *
from ..model.credit import *
from ..model.batch import *
from ..workflow import task
from ..workflow.parameter import *
from ..database.logger import  log 
from db2_utils import DB2 

import xlrd
log = logging.getLogger()
#.getLogger()
#log.basicConfig(level=logging.DEBUG)
#unittest.TestCase
class BranGrpTell():

    def setUp(self):
        log.debug("执行setup")
        self.session=simple_session()
        #Base.metadata.drop_all(self.session.bind)
        #Base.metadata.create_all(self.session.bind)
    
    def loadCustomerinfo(self):   
        acert1 = CommonArgs(type=u"性别",field_type=1,field_name="SEX",value=u"男")
        acert2 = CommonArgs(type=u"性别",field_type=2,field_name="SEX",value=u"女")
        acert3 = CommonArgs(type=u"性别",field_type=3,field_name="SEX",value=u"未知")
        acert4 = CommonArgs(type=u"性别",field_type=4,field_name="SEX",value=u"未提供")
        self.session.add_all([acert1,acert2,acert3,acert4])
        bcert1 = CommonArgs(type=u"学历",field_type=10,field_name="EDUCATION",value=u"研究生")
        bcert2 = CommonArgs(type=u"学历",field_type=20,field_name="EDUCATION",value=u"大学")
        bcert3 = CommonArgs(type=u"学历",field_type=30,field_name="EDUCATION",value=u"大专")
        bcert4 = CommonArgs(type=u"学历",field_type=40,field_name="EDUCATION",value=u"中专")
        bcert5 = CommonArgs(type=u"学历",field_type=50,field_name="EDUCATION",value=u"技术学校")
        bcert6 = CommonArgs(type=u"学历",field_type=60,field_name="EDUCATION",value=u"高中")
        bcert7 = CommonArgs(type=u"学历",field_type=70,field_name="EDUCATION",value=u"初中")
        bcert8 = CommonArgs(type=u"学历",field_type=80,field_name="EDUCATION",value=u"小学")
        bcert9 = CommonArgs(type=u"学历",field_type=90,field_name="EDUCATION",value=u"文盲或半文盲")
        bcert10 = CommonArgs(type=u"学历",field_type=99,field_name="EDUCATION",value=u"未知") 
        self.session.add_all([bcert1,bcert2,bcert3,bcert4,bcert5,bcert6,bcert7,bcert8,bcert9,bcert10]) 
        zcer1 = CommonArgs(type=u"学位",field_type=1,field_name="DEGREE",value=u"学士")
        zcer2 = CommonArgs(type=u"学位",field_type=2,field_name="DEGREE",value=u"硕士")
        zcer3 = CommonArgs(type=u"学位",field_type=3,field_name="DEGREE",value=u"博士")
        zcer4 = CommonArgs(type=u"学位",field_type=9,field_name="DEGREE",value=u"")
        self.session.add_all([zcer1,zcer2,zcer3,zcer4])               
        cet01 = CommonArgs(type=u"民族",field_type='1',field_name="NATIONALITY",value=u"汉族")
        cet02 = CommonArgs(type=u"民族",field_type='2',field_name="NATIONALITY",value=u"满族")
        cet03 = CommonArgs(type=u"民族",field_type='3',field_name="NATIONALITY",value=u"蒙古族")
        cet04 = CommonArgs(type=u"民族",field_type='4',field_name="NATIONALITY",value=u"回族")
        cet05 = CommonArgs(type=u"民族",field_type='5',field_name="NATIONALITY",value=u"其他")
        self.session.add_all([cet01,cet02,cet03,cet04,cet05])               
        crt1 = CommonArgs(type=u"健康状况",field_type='1',field_name="HEALTH_STATUS",value=u"健康")
        crt2 = CommonArgs(type=u"健康状况",field_type='2',field_name="HEALTH_STATUS",value=u"一般")
        crt3 = CommonArgs(type=u"健康状况",field_type='3',field_name="HEALTH_STATUS",value=u"不健康")
        self.session.add_all([crt1,crt2,crt3])                
        ert01 = CommonArgs(type=u"从事职业",field_type='1',field_name="OCCUPATION",value=u"公务员")
        ert02 = CommonArgs(type=u"从事职业",field_type='2',field_name="OCCUPATION",value=u"教育")
        ert03 = CommonArgs(type=u"从事职业",field_type='3',field_name="OCCUPATION",value=u"医疗卫生")
        ert04 = CommonArgs(type=u"从事职业",field_type='4',field_name="OCCUPATION",value=u"金融")
        ert05 = CommonArgs(type=u"从事职业",field_type='5',field_name="OCCUPATION",value=u"贸易")
        ert06 = CommonArgs(type=u"从事职业",field_type='6',field_name="OCCUPATION",value=u"高科技")
        ert07 = CommonArgs(type=u"从事职业",field_type='7',field_name="OCCUPATION",value=u"交通运输业")
        ert08 = CommonArgs(type=u"从事职业",field_type='8',field_name="OCCUPATION",value=u"服务业")
        ert09 = CommonArgs(type=u"从事职业",field_type='9',field_name="OCCUPATION",value=u"房地产业")
        ert10 = CommonArgs(type=u"从事职业",field_type='10',field_name="OCCUPATION",value=u"学生")
        ert11 = CommonArgs(type=u"从事职业",field_type='11',field_name="OCCUPATION",value=u"农民")
        ert12 = CommonArgs(type=u"从事职业",field_type='12',field_name="OCCUPATION",value=u"工人")
        ert13 = CommonArgs(type=u"从事职业",field_type='13',field_name="OCCUPATION",value=u"自由职业者")
        ert14 = CommonArgs(type=u"从事职业",field_type='14',field_name="OCCUPATION",value=u"无职业")
        ert15 = CommonArgs(type=u"从事职业",field_type='15',field_name="OCCUPATION",value=u"其它")
        self.session.add_all([ert01,ert02,ert03,ert04,ert05,ert06,ert07,ert08,ert09,ert10,ert11,ert12,ert13,ert14,ert15]) 
        certq01 = CommonArgs(type=u"政治面貌",field_type='1',field_name="POLITICAL_STATUS",value=u"党员")
        certq02 = CommonArgs(type=u"政治面貌",field_type='2',field_name="POLITICAL_STATUS",value=u"群众")
        self.session.add_all([certq01,certq02])               
        certw01 = CommonArgs(type=u"婚姻状况",field_type='1',field_name="MARRIAGE_STATUS",value=u"已婚")
        certw02 = CommonArgs(type=u"婚姻状况",field_type='2',field_name="MARRIAGE_STATUS",value=u"未婚")
        certw03 = CommonArgs(type=u"婚姻状况",field_type='3',field_name="MARRIAGE_STATUS",value=u"离异")
        certw04 = CommonArgs(type=u"婚姻状况",field_type='4',field_name="MARRIAGE_STATUS",value=u"丧偶")
        certw05 = CommonArgs(type=u"婚姻状况",field_type='5',field_name="MARRIAGE_STATUS",value=u"初婚")
        certw06 = CommonArgs(type=u"婚姻状况",field_type='6',field_name="MARRIAGE_STATUS",value=u"再婚")
        certw07 = CommonArgs(type=u"婚姻状况",field_type='7',field_name="MARRIAGE_STATUS",value=u"复婚")
        certw08 = CommonArgs(type=u"婚姻状况",field_type='8',field_name="MARRIAGE_STATUS",value=u"未说明")
        self.session.add_all([certw01,certw02,certw03,certw04,certw05,certw06,certw07,certw08])
        certe51 = CommonArgs(type=u"证件类型",field_type='51',field_name="ID_TYPE",value=u"身份证")
        certe52 = CommonArgs(type=u"证件类型",field_type='52',field_name="ID_TYPE",value=u"居民户口簿")
        certe53 = CommonArgs(type=u"证件类型",field_type='53',field_name="ID_TYPE",value=u"外国护照")
        certe54 = CommonArgs(type=u"证件类型",field_type='54',field_name="ID_TYPE",value=u"军人身份证")
        certe55 = CommonArgs(type=u"证件类型",field_type='55',field_name="ID_TYPE",value=u"武装警察身份证")
        certe56 = CommonArgs(type=u"证件类型",field_type='56',field_name="ID_TYPE",value=u"其他")
        self.session.add_all([certe51,certe52,certe53,certe54,certe55,certe56]) 
        certr01 = CommonArgs(type=u"持卡情况",field_type='1',field_name="PER_CREDIT_CARD",value=u"有本行卡")
        certr02 = CommonArgs(type=u"持卡情况",field_type='2',field_name="PER_CREDIT_CARD",value=u"有他行卡")
        certr99 = CommonArgs(type=u"持卡情况",field_type='99',field_name="PER_CREDIT_CARD",value=u"无卡") 
        self.session.add_all([certr01,certr02,certr99])
        certt01 = CommonArgs(type=u"单位性质",field_type='1',field_name="COM_TYPE",value=u"国有")
        certt02 = CommonArgs(type=u"单位性质",field_type='2',field_name="COM_TYPE",value=u"国有控股")
        certt03 = CommonArgs(type=u"单位性质",field_type='9',field_name="COM_TYPE",value=u"")
        certt04 = CommonArgs(type=u"单位性质",field_type='3',field_name="COM_TYPE",value=u"")
        certt10 = CommonArgs(type=u"单位性质",field_type='10',field_name="COM_TYPE",value =u"")
        self.session.add_all([certt01,certt02,certt03,certt04,certt10])                       
        certy101 = CommonArgs(type=u"单位所属行业",field_type='101',field_name="COM_FIELD",value=u"农、林、牧、渔业")
        certy102 = CommonArgs(type=u"单位所属行业",field_type='102',field_name="COM_FIELD",value=u"养殖业")
        certy208 = CommonArgs(type=u"单位所属行业",field_type='208',field_name="COM_FIELD",value=u"房地产业")
        certy103 = CommonArgs(type=u"单位所属行业",field_type='103',field_name="COM_FIELD",value=u"采掘业")
        certy104 = CommonArgs(type=u"单位所属行业",field_type='104',field_name="COM_FIELD",value=u"制造业")
        certy105 = CommonArgs(type=u"单位所属行业",field_type='105',field_name="COM_FIELD",value=u"电力、燃气及水的生产和供应业")
        certy106 = CommonArgs(type=u"单位所属行业",field_type='106',field_name="COM_FIELD",value=u"建筑业")
        certy107 = CommonArgs(type=u"单位所属行业",field_type='107',field_name="COM_FIELD",value=u"交通运输、 仓储和邮政业")
        certy108 = CommonArgs(type=u"单位所属行业",field_type='108',field_name="COM_FIELD",value=u"信息传输、计算机服务和软件业")
        certy109 = CommonArgs(type=u"单位所属行业",field_type='109',field_name="COM_FIELD",value=u"批发、零售业")
        certy200 = CommonArgs(type=u"单位所属行业",field_type='200',field_name="COM_FIELD",value=u"住宿和餐饮业")
        certy201 = CommonArgs(type=u"单位所属行业",field_type='201',field_name="COM_FIELD",value=u"金融业")
        certy203 = CommonArgs(type=u"单位所属行业",field_type='203',field_name="COM_FIELD",value=u"租赁和商务服务业")
        certy205 = CommonArgs(type=u"单位所属行业",field_type='205',field_name="COM_FIELD",value=u"水利、环境和公共设施管理业")
        certy202 = CommonArgs(type=u"单位所属行业",field_type='202',field_name="COM_FIELD",value=u"科学研究、技术服务业和地质勘查业")
        certy204 = CommonArgs(type=u"单位所属行业",field_type='204',field_name="COM_FIELD",value=u"居民服务和其他服务业")
        certy206 = CommonArgs(type=u"单位所属行业",field_type='206',field_name="COM_FIELD",value=u"教育")
        certy209 = CommonArgs(type=u"单位所属行业",field_type='209',field_name="COM_FIELD",value=u"卫生、社会保障和社会福利业")
        certy207 = CommonArgs(type=u"单位所属行业",field_type='207',field_name="COM_FIELD",value=u"文化、体育和娱乐业")
        certy300 = CommonArgs(type=u"单位所属行业",field_type='300',field_name="COM_FIELD",value=u"公共管理和社会组织")
        certy301 = CommonArgs(type=u"单位所属行业",field_type='301',field_name="COM_FIELD",value=u"国际组织")
        certy302 = CommonArgs(type=u"单位所属行业",field_type='302',field_name="COM_FIELD",value=u"其他")
        self.session.add_all([certy101,certy102,certy208,certy103,certy104,certy105,certy106,certy107,certy108,certy109,certy200,certy201,certy203,certy205,certy202,certy204,certy206,certy209,certy207,certy300,certy301,certy302])                         
        certi1 = CommonArgs(type=u"职务",field_type='1',field_name="JOB_TITLE",value=u"高级领导")
        certi2 = CommonArgs(type=u"职务",field_type='2',field_name="JOB_TITLE",value=u"中级领导")
        certi3 = CommonArgs(type=u"职务",field_type='3',field_name="JOB_TITLE",value=u"一般员工")
        certi4 = CommonArgs(type=u"职务",field_type='4',field_name="JOB_TITLE",value=u"其他")
        certi9 = CommonArgs(type=u"职务",field_type='9',field_name="JOB_TITLE",value=u"未知")
        self.session.add_all([certi1,certi2,certi3,certi4,certi9]) 
        certo0 = CommonArgs(type=u"是否在我行代发工资",field_type='0',field_name="BWAGE",value=u"否")
        certo1 = CommonArgs(type=u"是否在我行代发工资",field_type='1',field_name="BWAGE",value=u"是")
        self.session.add_all([certo0,certo1]) 
        certp1 = CommonArgs(type=u"居住状况",field_type='1',field_name="LIVE_INFO",value=u"自置")
        certp2 = CommonArgs(type=u"居住状况",field_type='2',field_name="LIVE_INFO",value=u"按揭")
        certp3 = CommonArgs(type=u"居住状况",field_type='3',field_name="LIVE_INFO",value=u"亲属楼宇")
        certp4 = CommonArgs(type=u"居住状况",field_type='4',field_name="LIVE_INFO",value=u"集体宿舍")
        certp5 = CommonArgs(type=u"居住状况",field_type='5',field_name="LIVE_INFO",value=u"租房")
        certp6 = CommonArgs(type=u"居住状况",field_type='6',field_name="LIVE_INFO",value=u"共有住宅")
        certp7 = CommonArgs(type=u"居住状况",field_type='7',field_name="LIVE_INFO",value=u"其他")
        certp9 = CommonArgs(type=u"居住状况",field_type='9',field_name="LIVE_INFO",value=u"未知")
        self.session.add_all([certp1,certp2,certp3,certp4,certp5,certp6,certp7,certp9]) 
        cercer1 = CommonArgs(type=u"法律责任形式",field_type="1",field_name="COM_LAW_DUTY",value=u"有限责任公司")
        cercer2 = CommonArgs(type=u"法律责任形式",field_type="2",field_name="COM_LAW_DUTY",value=u"股份有限公司")
        cercer9 = CommonArgs(type=u"法律责任形式",field_type="9",field_name="COM_LAW_DUTY",value=u"其他")
        self.session.add_all([cercer1,cercer2,cercer9]) 
        vbcer10 = CommonArgs(type=u"客户所属领域",field_type="10",field_name="CUS_FIELD",value=u"生产流通")
        vbcer20 = CommonArgs(type=u"客户所属领域",field_type="20",field_name="CUS_FIELD",value=u"非生产流通")
        self.session.add_all([vbcer10,vbcer20]) 
        ce99 = CommonArgs(type=u"客户种类",field_type="99",field_name="CUS_KIND",value=u"个人")
        ce1 = CommonArgs(type=u"客户种类",field_type="1",field_name="CUS_KIND",value=u"工业")
        ce2 = CommonArgs(type=u"客户种类",field_type="2",field_name="CUS_KIND",value=u"商业")
        ce3 = CommonArgs(type=u"客户种类",field_type="3",field_name="CUS_KIND",value=u"建筑业")
        ce4 = CommonArgs(type=u"客户种类",field_type="4",field_name="CUS_KIND",value=u"农业")
        ce5 = CommonArgs(type=u"客户种类",field_type="5",field_name="CUS_KIND",value=u"乡镇企业")
        ce6 = CommonArgs(type=u"客户种类",field_type="6",field_name="CUS_KIND",value=u"私营企业")
        ce7 = CommonArgs(type=u"客户种类",field_type="7",field_name="CUS_KIND",value=u"其他")
        self.session.add_all([ce99,ce1,ce2,ce3,ce4,ce5,ce6,ce7]) 
        c1 = CommonArgs(type=u"法人类型",field_type="1",field_name="CORP_TYPE",value=u"企业法人")
        c2 = CommonArgs(type=u"法人类型",field_type="2",field_name="CORP_TYPE",value=u"事业法人")
        c3 = CommonArgs(type=u"法人类型",field_type="3",field_name="CORP_TYPE",value=u"机关法人")
        c4 = CommonArgs(type=u"法人类型",field_type="4",field_name="CORP_TYPE",value=u"其他法人")
        self.session.add_all([c1,c2,c3,c4])         
        e1 = CommonArgs(type=u"法人是否持有商业信用卡",field_type="0",field_name="REP_CREDIT_CARD",value=u"否")
        e2 = CommonArgs(type=u"法人是否持有商业信用卡",field_type="1",field_name="REP_CREDIT_CARD",value=u"是")
        self.session.add_all([e1,e2])
        a1 = CommonArgs(type=u"营业执照年审结果",field_type="1",field_name="REG_CHECK_RESULT",value=u"年审合格")
        a2 = CommonArgs(type=u"营业执照年审结果",field_type="2",field_name="REG_CHECK_RESULT",value=u"经补证年审不合格")
        a3 = CommonArgs(type=u"营业执照年审结果",field_type="3",field_name="REG_CHECK_RESULT",value=u"年审不合格")
        a4 = CommonArgs(type=u"营业执照年审结果",field_type="4",field_name="REG_CHECK_RESULT",value=u"不参加当年年审")
        self.session.add_all([a1,a2,a3,a4]) 
        b1 = CommonArgs(type=u"注册币种",field_type="1",field_name="REG_CUR_TYPE",value=u"人民币")
        b2 = CommonArgs(type=u"注册币种",field_type="12",field_name="REG_CUR_TYPE",value=u"英镑")
        b3 = CommonArgs(type=u"注册币种",field_type="13",field_name="REG_CUR_TYPE",value=u"港币")
        b4 = CommonArgs(type=u"注册币种",field_type="14",field_name="REG_CUR_TYPE",value=u"美元")
        b5 = CommonArgs(type=u"注册币种",field_type="15",field_name="REG_CUR_TYPE",value=u"瑞士法郎")
        b6 = CommonArgs(type=u"注册币种",field_type="27",field_name="REG_CUR_TYPE",value=u"日元")
        b7 = CommonArgs(type=u"注册币种",field_type="28",field_name="REG_CUR_TYPE",value=u"加元")
        b8 = CommonArgs(type=u"注册币种",field_type="29",field_name="REG_CUR_TYPE",value=u"澳元")
        b9 = CommonArgs(type=u"注册币种",field_type="38",field_name="REG_CUR_TYPE",value=u"欧元")
        self.session.add_all([b1,b2,b3,b4,b5,b6,b7,b8,b9]) 
        c1 = CommonArgs(type=u"注册地所在国家地区",field_type="CHN",field_name="REG_COUNTRY",value=u"中国")
        c2 = CommonArgs(type=u"注册地所在国家地区",field_type="DEU",field_name="REG_COUNTRY",value=u"德国")
        c3 = CommonArgs(type=u"注册地所在国家地区",field_type="FRA",field_name="REG_COUNTRY",value=u"法国")
        c4 = CommonArgs(type=u"注册地所在国家地区",field_type="HKG",field_name="REG_COUNTRY",value=u"香港")
        c5 = CommonArgs(type=u"注册地所在国家地区",field_type="JPN",field_name="REG_COUNTRY",value=u"日本")
        c6 = CommonArgs(type=u"注册地所在国家地区",field_type="OTH",field_name="REG_COUNTRY",value=u"其他")
        c7 = CommonArgs(type=u"注册地所在国家地区",field_type="TWN",field_name="REG_COUNTRY",value=u"台湾")
        c8 = CommonArgs(type=u"注册地所在国家地区",field_type="USA",field_name="REG_COUNTRY",value=u"美国")
        self.session.add_all([c1,c2,c3,c4,c5,c6,c7,c8]) 
        d1 = CommonArgs(type=u"经营组织形式",field_type="10",field_name="OPT_TYPE",value=u"股份有限公司")
        d2 = CommonArgs(type=u"经营组织形式",field_type="20",field_name="OPT_TYPE",value=u"有限责任公司")
        d3 = CommonArgs(type=u"经营组织形式",field_type="30",field_name="OPT_TYPE",value=u"国有独资企业")
        d4 = CommonArgs(type=u"经营组织形式",field_type="40",field_name="OPT_TYPE",value=u"三资企业 ")
        d5 = CommonArgs(type=u"经营组织形式",field_type="50",field_name="OPT_TYPE",value=u"民营私营企业")
        d6 = CommonArgs(type=u"经营组织形式",field_type="60",field_name="OPT_TYPE",value=u"集体企业")
        d7 = CommonArgs(type=u"经营组织形式",field_type="70",field_name="OPT_TYPE",value=u"事业单位")
        d8 = CommonArgs(type=u"经营组织形式",field_type="80",field_name="OPT_TYPE",value=u"政府机构")
        d9 = CommonArgs(type=u"经营组织形式",field_type="90",field_name="OPT_TYPE",value=u"其他")
        self.session.add_all([d1,d2,d3,d4,d5,d6,d7,d8,d9]) 
        e1 = CommonArgs(type=u"企业规模",field_type="1",field_name="OPT_CAPITAL",value=u"大型")
        e2 = CommonArgs(type=u"企业规模",field_type="2",field_name="OPT_CAPITAL",value=u"中型")
        e3 = CommonArgs(type=u"企业规模",field_type="3",field_name="OPT_CAPITAL",value=u"小型")
        e4 = CommonArgs(type=u"企业规模",field_type="4",field_name="OPT_CAPITAL",value=u"微型")
        e5 = CommonArgs(type=u"企业规模",field_type="99",field_name="OPT_CAPITAL",value=u"其他")
        self.session.add_all([e1,e2,e3,e4,e5]) 
        f1 = CommonArgs(type=u"基本账户开户行",field_type="1",field_name="BASE_BANK",value=u"我行")
        f2 = CommonArgs(type=u"基本账户开户行",field_type="2",field_name="BASE_BANK",value=u"工行")
        f3 = CommonArgs(type=u"基本账户开户行",field_type="3",field_name="BASE_BANK",value=u"农行")
        f4 = CommonArgs(type=u"基本账户开户行",field_type="4",field_name="BASE_BANK",value=u"建行")
        f5 = CommonArgs(type=u"基本账户开户行",field_type="5",field_name="BASE_BANK",value=u"中行")
        f6 = CommonArgs(type=u"基本账户开户行",field_type="6",field_name="BASE_BANK",value=u"交行")
        f7 = CommonArgs(type=u"基本账户开户行",field_type="7",field_name="BASE_BANK",value=u"招行")
        f8 = CommonArgs(type=u"基本账户开户行",field_type="8",field_name="BASE_BANK",value=u"浦发行")
        f9 = CommonArgs(type=u"基本账户开户行",field_type="9",field_name="BASE_BANK",value=u"其他行")
        self.session.add_all([f1,f2,f3,f4,f5,f6,f7,f8,f9]) 
        g1 = CommonArgs(type=u"贷款卡标记",field_type="1",field_name="BLOAN_CARD",value=u"有效")
        g2 = CommonArgs(type=u"贷款卡标记",field_type="2",field_name="BLOAN_CARD",value=u"暂停")
        g3 = CommonArgs(type=u"贷款卡标记",field_type="3",field_name="BLOAN_CARD",value=u"注销")
        g4 = CommonArgs(type=u"贷款卡标记",field_type="4",field_name="BLOAN_CARD",value=u"吊销")
        self.session.add_all([g1,g2,g3,g4])           
        h1 = CommonArgs(type=u"异地企业标识",field_type="0",field_name="BGROUP",value=u"否")
        h2 = CommonArgs(type=u"异地企业标识",field_type="1",field_name="BGROUP",value=u"是")
        self.session.add_all([h1,h2])          
        j1 = CommonArgs(type=u"集团客户标志",field_type="0",field_name="BGROUP",value=u"否")
        j2 = CommonArgs(type=u"集团客户标志",field_type="1",field_name="BGROUP",value=u"是")
        self.session.add_all([j1,j2])        
        k1 = CommonArgs(type=u"集团管理模式",field_type="1",field_name="GROUP_MANAGE",value=u"母子公司制集团公司")
        k2 = CommonArgs(type=u"集团管理模式",field_type="2",field_name="GROUP_MANAGE",value=u"分制集团公司")
        self.session.add_all([k1,k2]) 
        l1 = CommonArgs(type=u"集团融资形式",field_type="1",field_name="GROUP_FINANCING",value=u"集团公司统一融资")
        l2 = CommonArgs(type=u"集团融资形式",field_type="2",field_name="GROUP_FINANCING",value=u"母子公司单独融资")
        l3 = CommonArgs(type=u"集团融资形式",field_type="3",field_name="GROUP_FINANCING",value=u"只有子公司对外融资")
        self.session.add_all([l1,l2,l3]) 
        m1 = CommonArgs(type=u"进出口权标识",field_type="0",field_name="BIMPORT_EXPORT",value=u"否")
        m2 = CommonArgs(type=u"进出口权标识",field_type="1",field_name="BIMPORT_EXPORT",value=u"是")
        self.session.add_all([m1,m2]) 
        n1 = CommonArgs(type=u"特种许可证是否有效",field_type="0",field_name="SP_LICENCE",value=u"否")
        n2 = CommonArgs(type=u"特种许可证是否有效",field_type="1",field_name="SP_LICENCE",value=u"是")
        self.session.add_all([n1,n2]) 
        z1 = CommonArgs(type=u"房地产开发企业类别",field_type="10",field_name="REAL_TYPE",value=u"综合类房地产开发企业")
        z2 = CommonArgs(type=u"房地产开发企业类别",field_type="20",field_name="REAL_TYPE",value=u"项目公司")
        z3 = CommonArgs(type=u"房地产开发企业类别",field_type="30",field_name="REAL_TYPE",value=u"其他")
        self.session.add_all([z1,z2,z3])       
        x1 = CommonArgs(type=u"是否通过环评",field_type="0",field_name="BFLAG1",value=u"否")
        x2 = CommonArgs(type=u"是否通过环评",field_type="1",field_name="BFLAG1",value=u"是")
        self.session.add_all([x1,x2])       
        v1 = CommonArgs(type=u"是否是市10家重点企",field_type="0",field_name="BFLAG2",value=u"否")
        v2 = CommonArgs(type=u"是否是市10家重点企",field_type="1",field_name="BFLAG2",value=u"是")
        self.session.add_all([v1,v2])           
        zb1 = CommonArgs(type=u"是否是市22家优势企",field_type="0",field_name="BFLAG3",value=u"否")
        zb2 = CommonArgs(type=u"是否是市22家优势企",field_type="1",field_name="BFLAG3",value=u"是")
        self.session.add_all([zb1,zb2])           
        qa1 = CommonArgs(type=u"是否是市60家成长企",field_type="0",field_name="BFLAG4",value=u"否")
        qa2 = CommonArgs(type=u"是否是市60家成长企",field_type="1",field_name="BFLAG4",value=u"是")
        self.session.add_all([qa1,qa2])          
        qw1 = CommonArgs(type=u"信用等级评定分类",field_type="11",field_name="IN_RATING_METHOD",value=u"工业(化工)")
        qw2 = CommonArgs(type=u"信用等级评定分类",field_type="12",field_name="IN_RATING_METHOD",value=u"工业(电子通讯)")
        qw3 = CommonArgs(type=u"信用等级评定分类",field_type="13",field_name="IN_RATING_METHOD",value=u"工业(机械制造)")
        qw4 = CommonArgs(type=u"信用等级评定分类",field_type="14",field_name="IN_RATING_METHOD",value=u"工业(冶金)")
        qw5 = CommonArgs(type=u"信用等级评定分类",field_type="15",field_name="IN_RATING_METHOD",value=u"工业(纺织服装)")
        qw6 = CommonArgs(type=u"信用等级评定分类",field_type="16",field_name="IN_RATING_METHOD",value=u"工业(其他)")
        qw7 = CommonArgs(type=u"信用等级评定分类",field_type="17",field_name="IN_RATING_METHOD",value=u"工业(建材)")
        qw8 = CommonArgs(type=u"信用等级评定分类",field_type="20",field_name="IN_RATING_METHOD",value=u"中介服务业")
        qw9 = CommonArgs(type=u"信用等级评定分类",field_type="30",field_name="IN_RATING_METHOD",value=u"公用事业")
        qw10 = CommonArgs(type=u"信用等级评定分类",field_type="40",field_name="IN_RATING_METHOD",value=u"交通运输业")
        qw11 = CommonArgs(type=u"信用等级评定分类",field_type="50",field_name="IN_RATING_METHOD",value=u"投资管理类")
        qw12 = CommonArgs(type=u"信用等级评定分类",field_type="60",field_name="IN_RATING_METHOD",value=u"事业单位")
        qw13 = CommonArgs(type=u"信用等级评定分类",field_type="70",field_name="IN_RATING_METHOD",value=u"施工业")
        qw14 = CommonArgs(type=u"信用等级评定分类",field_type="80",field_name="IN_RATING_METHOD",value=u"宾馆餐饮业")
        qw15 = CommonArgs(type=u"信用等级评定分类",field_type="91",field_name="IN_RATING_METHOD",value=u"商业(批发)")
        qw16 = CommonArgs(type=u"信用等级评定分类",field_type="92",field_name="IN_RATING_METHOD",value=u"商业(零售)")
        qw17 = CommonArgs(type=u"信用等级评定分类",field_type="101",field_name="IN_RATING_METHOD",value=u"综合")
        qw18 = CommonArgs(type=u"信用等级评定分类",field_type="110",field_name="IN_RATING_METHOD",value=u"房地产业")
        self.session.add_all([qw1,qw2,qw3,qw4,qw5,qw6,qw7,qw8,qw9,qw10,qw11,qw12,qw13,qw14,qw15,qw16,qw17,qw18])          
        qe1 = CommonArgs(type=u"本行即期信用等级",field_type="15",field_name="IN_CREDIT_CLASS",value=u"AAA")
        qe2 = CommonArgs(type=u"本行即期信用等级",field_type="25",field_name="IN_CREDIT_CLASS",value=u"AA")
        qe3 = CommonArgs(type=u"本行即期信用等级",field_type="35",field_name="IN_CREDIT_CLASS",value=u"A")
        qe4 = CommonArgs(type=u"本行即期信用等级",field_type="45",field_name="IN_CREDIT_CLASS",value=u"BBB")
        qe5 = CommonArgs(type=u"本行即期信用等级",field_type="55",field_name="IN_CREDIT_CLASS",value=u"BB")
        qe6 = CommonArgs(type=u"本行即期信用等级",field_type="65",field_name="IN_CREDIT_CLASS",value=u"B")
        qe7 = CommonArgs(type=u"本行即期信用等级",field_type="75",field_name="IN_CREDIT_CLASS",value=u"C")
        qe8 = CommonArgs(type=u"本行即期信用等级",field_type="99",field_name="IN_CREDIT_CLASS",value=u"未评级")
        self.session.add_all([qe1,qe2,qe3,qe4,qe5,qe6,qe7,qe8])            
        qr1 = CommonArgs(type=u"外部评级结果",field_type="15",field_name="OUT_CREDIT_CLASS",value=u"AAA")
        qr2 = CommonArgs(type=u"外部评级结果",field_type="25",field_name="OUT_CREDIT_CLASS",value=u"AA")
        qr3 = CommonArgs(type=u"外部评级结果",field_type="35",field_name="OUT_CREDIT_CLASS",value=u"A")
        qr4 = CommonArgs(type=u"外部评级结果",field_type="45",field_name="OUT_CREDIT_CLASS",value=u"BBB")
        qr5 = CommonArgs(type=u"外部评级结果",field_type="55",field_name="OUT_CREDIT_CLASS",value=u"BB")
        qr6 = CommonArgs(type=u"外部评级结果",field_type="65",field_name="OUT_CREDIT_CLASS",value=u"B")
        qr7 = CommonArgs(type=u"外部评级结果",field_type="75",field_name="OUT_CREDIT_CLASS",value=u"C")
        qr8 = CommonArgs(type=u"外部评级结果",field_type="99",field_name="OUT_CREDIT_CLASS",value=u"未评级")
        self.session.add_all([qr1,qr2,qr3,qr4,qr5,qr6,qr7,qr8])        
        qb1 = CommonArgs(type=u"与我行的关联关系",field_type="1",field_name="REL_DESC",value=u"内部人")
        qb2 = CommonArgs(type=u"与我行的关联关系",field_type="2",field_name="REL_DESC",value=u"持股5%以上的股东")
        qb3 = CommonArgs(type=u"与我行的关联关系",field_type="3",field_name="REL_DESC",value=u"内部人及股东的近亲属")
        qb4 = CommonArgs(type=u"与我行的关联关系",field_type="6",field_name="REL_DESC",value=u"一般关联关系")
        qb5 = CommonArgs(type=u"与我行的关联关系",field_type="9",field_name="REL_DESC",value=u"无关联关系")
        self.session.add_all([qb1,qb2,qb3,qb4,qb5])     
        qc1 = CommonArgs(type=u"与我行的合作关系",field_type="1",field_name="REL_DEGREE",value=u"非常密切")
        qc2 = CommonArgs(type=u"与我行的合作关系",field_type="2",field_name="REL_DEGREE",value=u"密切")
        qc3 = CommonArgs(type=u"与我行的合作关系",field_type="3",field_name="REL_DEGREE",value=u"一般")
        self.session.add_all([qc1,qc2,qc3])           
        qm1 = CommonArgs(type=u"是否拥有我行股权",field_type="0",field_name="BHOLD_STOCK",value=u"否")
        qm2 = CommonArgs(type=u"是否拥有我行股权",field_type="1",field_name="BHOLD_STOCK",value=u"是")
        self.session.add_all([qm1,qm2])       
        qo1 = CommonArgs(type=u"我行客户分类",field_type="1",field_name="BANK_CUS_TYPE",value=u"积极支持类")
        qo2 = CommonArgs(type=u"我行客户分类",field_type="2",field_name="BANK_CUS_TYPE",value=u"一般支持类")
        qo3 = CommonArgs(type=u"我行客户分类",field_type="3",field_name="BANK_CUS_TYPE",value=u"限制支持类")
        qo4 = CommonArgs(type=u"我行客户分类",field_type="4",field_name="BANK_CUS_TYPE",value=u"禁止支持类")
        self.session.add_all([qo1,qo2,qo3,qo4])         
        qp1 = CommonArgs(type=u"红灯客户标识",field_type="0",field_name="RISK_FLAG",value=u"否")
        qp2 = CommonArgs(type=u"红灯客户标识",field_type="1",field_name="RISK_FLAG",value=u"是")
        self.session.add_all([qp1,qp2])        
        qt1 = CommonArgs(type=u"黑名单客户标识",field_type="0",field_name="BLACKLIST_FLAG",value=u"否")
        qt2 = CommonArgs(type=u"黑名单客户标识",field_type="1",field_name="BLACKLIST_FLAG",value=u"是")
        self.session.add_all([qt1,qt2])
        qm1 = CommonArgs(type=u"土地性质",field_type="1",field_name="OPT_NATURE",value=u"国有出让")
        qm2 = CommonArgs(type=u"土地性质",field_type="2",field_name="OPT_NATURE",value=u"国有划拔")
        qm3 = CommonArgs(type=u"土地性质",field_type="3",field_name="OPT_NATURE",value=u"集体")
        self.session.add_all([qm1,qm2,qm3])         
        qk1 = CommonArgs(type=u"经营方式",field_type="1",field_name="OPT_FASHION",value=u"批发")
        qk2 = CommonArgs(type=u"经营方式",field_type="2",field_name="OPT_FASHION",value=u"零售")
        self.session.add_all([qk1,qk2])     
        qkwer1 = CommonArgs(type=u"客户类型",field_type="1",field_name="CUS_VARIETY",value=u"仅是基本户客户")
        qkwer2 = CommonArgs(type=u"客户类型",field_type="2",field_name="CUS_VARIETY",value=u"仅是信贷户客户")
        qkwer3 = CommonArgs(type=u"客户类型",field_type="3",field_name="CUS_VARIETY",value=u"既是基本户又是信贷户的客户")
        qkwer4 = CommonArgs(type=u"客户类型",field_type="X",field_name="CUS_VARIETY",value=u"未知")
        self.session.add_all([qkwer1,qkwer2,qkwer3,qkwer4])    
        qkwea1 = CommonArgs(type=u"企业状态",field_type="1",field_name="ORG_STATE",value=u"正常")
        qkwea2 = CommonArgs(type=u"企业状态",field_type="2",field_name="ORG_STATE",value=u"注销")
        qkwea3 = CommonArgs(type=u"企业状态",field_type="9",field_name="ORG_STATE",value=u"其他")
        self.session.add_all([qkwea1,qkwea2,qkwea3]) 
        '''       
        poi1 = CommonArgs(type=u"企业规模",field_type="1",field_name="OPT_CAPITAL",value=u"大型")
        poi2 = CommonArgs(type=u"企业规模",field_type="2",field_name="OPT_CAPITAL",value=u"中型")
        poi3 = CommonArgs(type=u"企业规模",field_type="3",field_name="OPT_CAPITAL",value=u"小型")
        poi4 = CommonArgs(type=u"企业规模",field_type="4",field_name="OPT_CAPITAL",value=u"微型")
        self.session.add_all([poi1,poi2,poi3,poi4])       
        
        poit1 = CommonArgs(type=u"客户类型",field_type="1",field_name="CUS_KIND",value=u"个人")
        poit2 = CommonArgs(type=u"客户类型",field_type="2",field_name="CUS_KIND",value=u"个体工商户")
        poit3 = CommonArgs(type=u"客户类型",field_type="3",field_name="CUS_KIND",value=u"公司客户业主")
        poit4 = CommonArgs(type=u"客户类型",field_type="4",field_name="CUS_KIND",value=u"小微企业主")
        poit5 = CommonArgs(type=u"客户类型",field_type="5",field_name="CUS_KIND",value=u"其他")
        self.session.add_all([poit1,poit2,poit3,poit4,poit5])
        '''

    def loadBranch(self):
    
        #  机构
        data = xlrd.open_workbook('../static/branch.xls')
        sheet = data.sheet_by_index(0)
        nrows = sheet.nrows
        branch = Branch(branch_code=u'048301',branch_name=u'阿拉善支行')
        self.session.add(branch)
        for r in range(4,nrows):
            branch = Branch(branch_code=sheet.cell(r,0).value,branch_name=sheet.cell(r,2).value,branch_totalname=sheet.cell(r,1).value,is_loan_branch=sheet.cell(r,3).value)
            log.debug(sheet.cell(r,0).value)
            log.debug(sheet.cell(r,1).value)
            log.debug(sheet.cell(r,2).value)
            log.debug(sheet.cell(r,3).value)
            self.session.add(branch)
        
        
        #岗位
        excel = xlrd.open_workbook('../static/teller_branch.xls')
        sheet = excel.sheet_by_index(1)
        g1 = sheet.cell(1,7).value.split(u'，')
        g2 = sheet.cell(1,8).value.split(u'，')
        g1.extend(g2)
        for g in g1:
            grp=Group(group_name=g)
            self.session.add(grp)
        #log.debug(g2)
        self.session.commit()
        '''
        g1 = Group(group_name=u"客户经理")
        g2 = Group(group_name=u"支行风险评价岗")
        g3 = Group(group_name=u"支行审查岗")
        g4 = Group(group_name=u"支行审贷小组")
        g5 = Group(group_name=u"支行行长")
        g6 = Group(group_name=u"总行审查岗")
        g7 = Group(group_name=u"总行审查负责人")
        g8 = Group(group_name=u"总行风险评价岗")
        g9 = Group(group_name=u"总行风险负责人")
        g10 = Group(group_name=u"总行审贷委")
        g11 = Group(group_name=u"分管信贷副行长")
        g12 = Group(group_name=u"总行行长")

        g13=Group(group_name=u"验票岗")
        g14=Group(group_name=u"会计部")

        g15=Group(group_name=u"投资交易岗")
        g16=Group(group_name=u"资金部风险岗")
        g17=Group(group_name=u"资金部负责人")
        g18=Group(group_name=u"财务部负责人")
        g19=Group(group_name=u"投资审议委员会")
        g20=Group(group_name=u"投资审议小组")
        g21 = Group(group_name=u"分管资金副行长")

        g22 = Group(group_name=u"同业交易岗")
        g23 = Group(group_name=u"营业部转贴现岗")
        g24 = Group(group_name=u"营业部转贴现负责人")
        g25 = Group(group_name=u"分管同业副行长")
        g26 = Group(group_name=u"投资交易复核岗")
       
        self.session.add_all(
        [g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13,g14,g15,g16,g17,g18,g19,g20,g21,g22,g23,g24,g25,g26])
        '''

    def teller_branch(self):
        ''' 用户 关联 机构 和 岗位 '''
        teller_branch = xlrd.open_workbook('../static/teller_branch.xls')
        sheet = teller_branch.sheet_by_index(1)
        nrows = sheet.nrows
        branch = self.session.query(Branch)
        group = self.session.query(Group)
        for r in range(3,nrows):
            log.debug(sheet.cell(r,0).value+':'+sheet.cell(r,1).value+':'+sheet.cell(r,4).value+':'+sheet.cell(r,5).value+':'+sheet.cell(r,6).value)
            v1=sheet.cell(r,0).value
            v2=sheet.cell(r,1).value
            v3=sheet.cell(r,4).value
            v4=sheet.cell(r,5).value
            v5=sheet.cell(r,6).value 
            if v5 in ['',None]:
                continue
            # 用户 添加
            usr = User(user_name=v1.strip(),name=v2.strip())
            ps = Password(user=usr,algorithm=u'MD5',credential=u'qwe123')
            self.session.add(ps)
            #usr = user.filter(User.user_name==v1.strip()).first()
            
            # 用户 ---  机构    关联
            brc = branch.filter(Branch.branch_code==v3.strip()).first()
            usr_brc = UserBranch(user=usr,branch=brc)
            self.session.add(usr_brc)

            # 用户 --- 岗位     关联
            g_list=[]
            tmp = v5.split(u'、')
            for one in tmp:
                g_list.extend(one.split(u'，'))
            gps = group.filter(Group.group_name.in_(g_list)).all()
            log.debug('**'*20)
            log.debug(gps)
            for gp in gps:
                usr_grp=UserGroup(user=usr,group=gp)
                self.session.add(usr_grp)
            #log.debug(gps)
        self.session.commit()

    def func(self,session):
        self.session = session
        self.loadCustomerinfo()
        self.loadBranch()    
        self.teller_branch()

    def tearDown(self):
        #self.session.commit()
        log.debug("Over")

